- name: number is less than 10
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: Please enter a number
    private: false
  tasks:
  - name: print if the number is less than 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number < 10

  - name: print if the number is greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is greater than or equal to 10"
    when: number >= 10