- name: filters/fuctions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "hello {{ course | default('ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "hello ramesh"    
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"

  - name: convert to lowercase
    vars:
      greeting: "hello ramesh"    
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"

  - name: get the unique values
    vars:
      numbers: [1,5,3,6,2,1,4,6,77,87,6,5]
    ansible.builtin.debug:
      msg: " {{ numbers | unique}}"

  - name: get the min value
    vars:
      numbers: [1,5,3,6,2,1,4,6,77,87,6,5]
    ansible.builtin.debug:
      msg: " {{ numbers | min}}"

  - name: get the max value
    vars:
      numbers: [1,5,3,6,2,1,4,6,77,87,6,5]
    ansible.builtin.debug:
      msg: " {{ numbers | max}}"

  - name: conver map to dictionary
    vars:
      map: 
        red:rose
        violet:lily
        yellow:chrymssum
    ansible.builtin.debug:
      msg: " {{ map | dict2items }}"

